### ISSUE TITLE
Add node prerequisite

### ISSUE THREAD

**Issue by astik** [lmtm/prez#17]
When trying 'prez --init' on node 5, I get this error :

```
> sandbox node -v
v5.3.0
> sandbox prez --init
/usr/local/lib/node_modules/prez/lib/cli.js:5
var { merge } = require("lodash/fp");
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/prez/bin/prez.js:7:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

Destructuring seems to be unavailable in Node 5, it needs a flag to work (node --harmony_destructuring).

Moving to Node 6 allow prez to work :

```
> sandbox node -v
v6.2.2
```

Documentation should reflect this prerequisite, either :
- a way to activate the harmony flag
- move to Node6

**Comment by Delapouite** [comment]
Thanks!

I've added a mention about node v6 in the README
https://github.com/byteclubfr/prez/commit/a57f3c4013124506447e575f02f08595384bd3eb

Also moe that node 5 EOL is in 10 days, at the end of June.

As prez is not a tool intended to be deployed on a server but rather used by individuals on their own dev machine, staying up to date with node version is quite easy thanks to https://github.com/creationix/nvm
