### ISSUE TITLE
Wrong syntax coloration behaviour

### ISSUE THREAD

**Issue by noraj** [lmtm/prez#22]
When writing multi-line code from markdown without specifying class there is syntax coloration but that shouldn't and the `no-highligt` class is not present.

And it seems there is not all highlight.js styles.

**Comment by noraj** [comment]
```
prez --serve
[warn] Source folder not specified: use cwd
[warn] Destination folder not specified: use 'build'
[info] copy ../../../../../../../usr/lib/node_modules/prez/data/dynamic-theme.js to build/js
[info] copy ../../../../../../../usr/lib/node_modules/prez/node_modules/reveal.js/css to build
[info] copy ../../../../../../../usr/lib/node_modules/prez/node_modules/reveal.js/js to build
[info] copy ../../../../../../../usr/lib/node_modules/prez/node_modules/reveal.js/lib to build
[info] copy ../../../../../../../usr/lib/node_modules/prez/node_modules/reveal.js/plugin to build
[info] copy ../../../../../../../usr/lib/node_modules/prez/node_modules/highlight.js/styles to build/css/highlight
[info] copy ../../../../../../../usr/lib/node_modules/prez/data/such-notes-print.js to build/js
[info] copy ../../../../../../../usr/lib/node_modules/prez/data/such-notes-print.css to build/css
[info] copy ../../../../../../../usr/lib/node_modules/prez/data/such-notes-popup.css to build/css
[info] copy ../../../../../../../usr/lib/node_modules/prez/data/such-notes-popup.js to build/js
[info] write build/plugin/notes/notes.html (10242 bytes)
[warn] cannot copy css (file not found)
[warn] cannot copy js (file not found)
[info] copy images to build
[warn] cannot copy media (file not found)
/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:1226
    throw e;
    ^

Error: Unknown language: "no-highligt"
Please report this to https://github.com/chjj/marked.
    at Object.highlight (/usr/lib/node_modules/prez/node_modules/highlight.js/lib/highlight.js:454:13)
    at Object.marked.highlight (/usr/lib/node_modules/prez/lib/parsers/marked.js:22:28)
    at Renderer.code (/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:766:28)
    at Parser.tok (/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:990:28)
    at Parser.tok (/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:1054:18)
    at Parser.tok (/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:1043:22)
    at Parser.parse (/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:935:17)
    at Function.Parser.parse (/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:922:17)
    at marked (/usr/lib/node_modules/prez/node_modules/marked/lib/marked.js:1218:19)
    at md2html (/usr/lib/node_modules/prez/lib/parsers/marked.js:18:10)
```

**Comment by Delapouite** [comment]
Hello. Where does `no-highligt` come from? There's a typo with a missing `h` at the end.

**Comment by noraj** [comment]
I don't even know ...
