### ISSUE TITLE
Error on watch

### ISSUE THREAD

**Issue by nbussman** [lmtm/prez#7]
Hey guys,
when I try to `prez --watch` or `prez --serve --watch`, I get the following error:

```
[info] copy ../../../../../../../../usr/local/lib/node_modules/prez/data/dynamic-theme.js to build/js
[info] copy ../../../../../../../../usr/local/lib/node_modules/prez/node_modules/reveal.js/css to build
[info] copy ../../../../../../../../usr/local/lib/node_modules/prez/node_modules/reveal.js/js to build
[info] copy ../../../../../../../../usr/local/lib/node_modules/prez/node_modules/reveal.js/lib to build
[info] copy ../../../../../../../../usr/local/lib/node_modules/prez/node_modules/reveal.js/plugin to     build
[info] copy ../../../../../../../../usr/local/lib/node_modules/prez/node_modules/highlight.js/styles     to build/css/highlight
[info] copy css to build
[info] copy js to build
[info] copy images to build
[info] copy media to build
[info] copy ../../../../../../../../usr/local/lib/node_modules/prez/data/index.html to build
[info] write build/index.html (3859 bytes)
[info] serve slideshows from build…
[info] started server live-reload on port 35729
[info] started server http on port 9000

fs.js:1062
    throw errnoException(process._errno, 'watch');
          ^
Error: watch EMFILE
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at watch (/usr/local/lib/node_modules/prez/node_modules/node-watch/lib/watch.js:221:8)
    at /usr/local/lib/node_modules/prez/node_modules/node-watch/lib/watch.js:230:9
    at /usr/local/lib/node_modules/prez/node_modules/node-watch/lib/watch.js:41:14
    at Array.forEach (native)
    at /usr/local/lib/node_modules/prez/node_modules/node-watch/lib/watch.js:38:18
    at Object.oncomplete (fs.js:107:15)
```

Can you may be help me with that? Thanks!

Cheer Nils

**Comment by nbussman** [comment]
I'm on a mac and this did the trick:

Execute this command one by one, and after that restart the computer
`
    echo 'kern.maxfiles=20480' | sudo tee -a /etc/sysctl.conf
    echo -e 'limit maxfiles 8192 20480\nlimit maxproc 1000 2000' | sudo tee -a /etc/launchd.conf
    echo 'ulimit -n 4096' | sudo tee -a /etc/profile
`
Even if there are still errors, it seems to work =)

**Comment by Delapouite** [comment]
Hello Nils.

What is your node version? 
How many markdown files do you have in your /slides folder?

**Comment by Delapouite** [comment]
It appears to be a platform specific problem. I'm closing this issue for now. Feel free to reopen it if needed.

**Comment by vallettea** [comment]
FYI: I add the same problem on OSX El Capitan and changing the ulimit did nothing. However moving from node 0.10 to node 4.2.4 did the trick.

**Comment by Delapouite** [comment]
Glad to hear it! Thanks for the feedback.

Future versions of prez may force recent versions of Node to be able to use ES6 niceties.
